# This is a basic workflow that is manually triggered

name: AutoDoc API

# Controls when the action will run.
on:
  workflow_dispatch:
  push:

jobs:
  rebuild_docs:
    runs-on: windows-latest
    
    steps:
    # Checkout the repository first
    - name: Checkout website repo
      uses: actions/checkout@v3
      with:
        repository: RazorEnhanced-UO/razorenhanced.github.io
        path: website_repo
    
    # Debug the working directory and structure
    - name: Debug directory structure
      run: |
        Write-Host "Current directory: $pwd"
        Write-Host "Directory contents at root:"
        Get-ChildItem
        Write-Host "Website repo directory contents:"
        Get-ChildItem website_repo
        Write-Host "Releases directory contents:"
        if (Test-Path "website_repo/releases") {
          Get-ChildItem website_repo/releases
        } else {
          Write-Host "Releases directory not found!"
        }
      shell: pwsh
    
    # Get the latest zip file directly from the repository
    - name: Find latest release file
      id: find_zip
      run: |
        # Check if releases directory exists
        if (-not (Test-Path "website_repo/releases")) {
          Write-Error "Releases directory not found!"
          exit 1
        }
        
        # Get the latest zip file by last modified date
        $latestZip = Get-ChildItem -Path "website_repo/releases" -Filter "RazorEnhanced-*.zip" | 
                     Where-Object { $_.Name -ne "RazorEnhanced-latest.zip" } |
                     Sort-Object -Property LastWriteTime -Descending | 
                     Select-Object -First 1
        
        if ($latestZip) {
          Write-Host "Found latest release: $($latestZip.Name)"
          Write-Host "Full path: $($latestZip.FullName)"
          echo "zip_file=$($latestZip.Name)" >> $env:GITHUB_OUTPUT
        } else {
          Write-Error "No release zip files found in the releases directory"
          exit 1
        }
      shell: pwsh
      
    # Extract the zip file
    - name: Extract the latest release
      run: |
        # Create extraction directory
        New-Item -ItemType Directory -Path "extracted" -Force
        
        # Extract the zip
        $zipPath = "website_repo/releases/${{ steps.find_zip.outputs.zip_file }}"
        Write-Host "Extracting: $zipPath"
        7z x "$zipPath" -o"./extracted"
      shell: pwsh
      
    - name: Display extracted files
      run: dir extracted
  
    # Try to run directly   
    - name: Run RE to trigger the creation of AutoComplete.json
      run: |
        cd extracted
        RazorEnhanced.exe --autoDocsOnly
        dir Config
      shell: cmd
    
    - name: Display directories
      run: dir extracted/Config/
      
    # Build Docs (use the AutoDoc.py file from the repository)
    - name: Run autodoc.py
      run: |
        cd extracted
        # Copy AutoDoc.py from the repository
        Copy-Item "../website_repo/doc/autodoc.py" -Destination "."
        # Run AutoDoc
        python autodoc.py
      shell: pwsh
    
    # Copy generated docs to the repository
    - name: Update repo documentation
      run: |
        Copy-Item -Path "extracted/doc/*" -Destination "website_repo/doc/" -Recurse -Force -Verbose
      shell: pwsh
    
    # Add, commit & push
    - name: Add, Commit & push
      uses: EndBug/add-and-commit@v9
      with:
        message: "GitHub Actions build_docs"
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        cwd: './website_repo'
        pathspec_error_handling: exitImmediately
        push: true